updates on azkar file , options time, logo
nagwan/zekr-remider-chrome-extension pull request #11
Opened 2023-03-28 15:26 UTC by m-1226

السلام عليكم ورحمة الله وبركاته 
قمت ببعض التعديلات البسيطة علي الإضافة 
1- ضفت أذكار جديدة لملف azkar.js  
2- غيرت الوقت اللي موجود في ال options ل 5 , 10 , 15 , 20 , 25 دقيقة علشان يكون وقت الذكر أقرب 
لإنه في تطبيقات الأذكار كلها اللي بستخدمها بيكون أقل وقت للذكر هو 5 دقائق وأقصي حاجة 30 دقيقة 
3- أضفت logo جديد بدل المعروض عند فتح الاضافة 

أرجو إن الإضافات دي تكون مفيدة ولو بشق تمرة بإذن الله

2023-03-28 18:50 UTC, HXN2 commented
اخوي تقدر تشوف حل المشكلة في ملف باك جراوند جافاسكريبت لان انبلشت فيه الصراحة

2023-03-28 18:53 UTC, m-1226 commented
> اخوي تقدر تشوف حل المشكلة في ملف باك جراوند جافاسكريبت لان انبلشت فيه الصراحة

بسيطة إن شاء الله
ايه المشكلة ؟

2023-03-28 19:11 UTC, m-1226 commented
> > > اخوي تقدر تشوف حل المشكلة في ملف باك جراوند جافاسكريبت لان انبلشت فيه الصراحة
> > 
> > بسيطة إن شاء الله ايه المشكلة ؟
> 
> كلمني تيليجرام اذا تقدر https://t.me/he_xn او حط ايميلك وانا حكلمك

بحاول ارسل لك علي telegram لكن بدون جدوي 
حسابي مقيد لجهات الاتصال الغير مسجلة عندي برقمها

2023-03-28 19:20 UTC, HXN2 commented
> > > > اخوي تقدر تشوف حل المشكلة في ملف باك جراوند جافاسكريبت لان انبلشت فيه الصراحة
> > > 
> > > 
> > > بسيطة إن شاء الله ايه المشكلة ؟
> > 
> > 
> > كلمني تيليجرام اذا تقدر https://t.me/he_xn او حط ايميلك وانا حكلمك
> 
> بحاول ارسل لك علي telegram لكن بدون جدوي حسابي مقيد لجهات الاتصال الغير مسجلة عندي برقمها

ارسل لك روح شوف

2023-05-05 06:35 UTC, HXN2 commented
السلام عليكم اخوي محمد اشرف اقدر اكلمك على التيليجرام مرة اخرى؟

2023-07-21 08:48 UTC, nagwan commented
@m-1226 
السلام عليكم ورحمه الله وبركاته 
شكرا جدا على اهتمامك بتطوير ال extension 
ولكن بعض التغييرات اللي ضفتها بتغير من هدف ال extension 
خليني اناقش معاك بعض منهم 

- اضافه اذكار جديده شيء رائع و هتاكد اني اضيفهم ان شاء الله 
- تغيير الوقت اللي موجود في ال options: خليني ااقولك ان اول نسخه من ال extension كان الوقت 10 دقايق و كان راي المستخدمين انو كده الوقت قليل جدا وتحول من انو حاجه تساعد الناس تذكر ربنا مع الوقت الكبير اللي بنقضيه على اللاب توب الي انو اصبح notification متكرره مزعجه بتخرجهم عن الحاجه اللي شغالين عليها بالفعل 
- بالنسبه لاضافه لوجو جديد شكرا لاهتمامك بالتفاصيل بس في مصمم هيشتغل على حاجه تكون خاصه بينا ان شاء الله 
- بالنسبه لل commit اللي مكتوب فيه تغييرات جذريه فهو بعيد كل البعد عن هدف ال extension لانو زي ما ذكرت لحضرتك قبل كده هدف ال extension هو ذكر بسيط وسط زحمه الشغل و اليوم فصعب جدا حد يقعد يقراء القميه بكل ذكر و خليني ااقولك ان في بدايه الامر كنا متعمدين نضيف اذكار قصيره محفوظه من كل الناس تقريبا و بالتالي اما يجي الاشعار المستخدم مش مضطر انو يقراء الذكر كامل و لكن بمجرد عينه ما تلمح اول كلمه يقدر يردد الذكر تلقائيا
- فكره اذكار الصباح و المساء اكثر من رائعه شكرا جدا للاضافه الجميله  

شكرا جدا مره تانيه على اهتمامك و مشركتك ربنا يتقبل منا و منكم صالح الاعمال
استاذنك ان امكن pr  جديد فقط بالاذاكار الاضافيه اللي حضرتك حابب تضيفها مع جزئئه اذكار الصباح و المساء اما جزئيه تغير التوقيت فمفيش مشكله من اضافه ٥ و ١٠ دقايق لل options لموجوده بالفعل

2023-07-21 09:23 UTC, nagwan requested changes
@m-1226
السلام عليكم ورحمه الله وبركاته
شكرا جدا على اهتمامك بتطوير ال extension
ولكن بعض التغييرات اللي ضفتها بتغير من هدف ال extension
خليني اناقش معاك بعض منهم

اضافه اذكار جديده شيء رائع و هتاكد اني اضيفهم ان شاء الله
تغيير الوقت اللي موجود في ال options: خليني ااقولك ان اول نسخه من ال extension كان الوقت 10 دقايق و كان راي المستخدمين انو كده الوقت قليل جدا وتحول من انو حاجه تساعد الناس تذكر ربنا مع الوقت الكبير اللي بنقضيه على اللاب توب الي انو اصبح notification متكرره مزعجه بتخرجهم عن الحاجه اللي شغالين عليها بالفعل فخلينا نضيف ال optionsلجديده مع الموجوده بالفعل 

بالنسبه لاضافه لوجو جديد شكرا لاهتمامك بالتفاصيل بس في مصمم هيشتغل على حاجه تكون خاصه بينا ان شاء الله

بالنسبه لل commit اللي مكتوب فيه تغييرات جذريه فهو بعيد كل البعد عن هدف ال extension لانو زي ما ذكرت لحضرتك قبل كده هدف ال extension هو ذكر بسيط وسط زحمه الشغل و اليوم فصعب جدا حد يقعد يقراء القميه بكل ذكر و خليني ااقولك ان في بدايه الامر كنا متعمدين نضيف اذكار قصيره محفوظه من كل الناس تقريبا و بالتالي اما يجي الاشعار المستخدم مش مضطر انو يقراء الذكر كامل و لكن بمجرد عينه ما تلمح اول كلمه يقدر يردد الذكر تلقائيا فعايزين نتجنب وجود كلام كتير داخل ال notification. 

فكره اذكار الصباح و المساء اكثر من رائعه شكرا جدا للاضافه الجميله
شكرا جدا مره تانيه على اهتمامك و مشركتك ربنا يتقبل منا و منكم صالح الاعمال

استاذنك ان امكن pr جديد فقط بالاذاكار الاضافيه اللي حضرتك حابب تضيفها مع جزئئه اذكار الصباح و المساء اما جزئيه تغير التوقيت فمفيش مشكله من اضافه ٥ و ١٠ دقايق لل options لموجوده بالفعل

2023-07-21 11:43 UTC, m-1226 commented
> @m-1226 السلام عليكم ورحمه الله وبركاته شكرا جدا على اهتمامك بتطوير ال extension ولكن بعض التغييرات اللي ضفتها بتغير من هدف ال extension خليني اناقش معاك بعض منهم
> 
> اضافه اذكار جديده شيء رائع و هتاكد اني اضيفهم ان شاء الله تغيير الوقت اللي موجود في ال options: خليني ااقولك ان اول نسخه من ال extension كان الوقت 10 دقايق و كان راي المستخدمين انو كده الوقت قليل جدا وتحول من انو حاجه تساعد الناس تذكر ربنا مع الوقت الكبير اللي بنقضيه على اللاب توب الي انو اصبح notification متكرره مزعجه بتخرجهم عن الحاجه اللي شغالين عليها بالفعل فخلينا نضيف ال optionsلجديده مع الموجوده بالفعل
> 
> بالنسبه لاضافه لوجو جديد شكرا لاهتمامك بالتفاصيل بس في مصمم هيشتغل على حاجه تكون خاصه بينا ان شاء الله
> 
> بالنسبه لل commit اللي مكتوب فيه تغييرات جذريه فهو بعيد كل البعد عن هدف ال extension لانو زي ما ذكرت لحضرتك قبل كده هدف ال extension هو ذكر بسيط وسط زحمه الشغل و اليوم فصعب جدا حد يقعد يقراء القميه بكل ذكر و خليني ااقولك ان في بدايه الامر كنا متعمدين نضيف اذكار قصيره محفوظه من كل الناس تقريبا و بالتالي اما يجي الاشعار المستخدم مش مضطر انو يقراء الذكر كامل و لكن بمجرد عينه ما تلمح اول كلمه يقدر يردد الذكر تلقائيا فعايزين نتجنب وجود كلام كتير داخل ال notification.
> 
> فكره اذكار الصباح و المساء اكثر من رائعه شكرا جدا للاضافه الجميله شكرا جدا مره تانيه على اهتمامك و مشركتك ربنا يتقبل منا و منكم صالح الاعمال
> 
> استاذنك ان امكن pr جديد فقط بالاذاكار الاضافيه اللي حضرتك حابب تضيفها مع جزئئه اذكار الصباح و المساء اما جزئيه تغير التوقيت فمفيش مشكله من اضافه ٥ و ١٠ دقايق لل options لموجوده بالفعل



> @m-1226 السلام عليكم ورحمه الله وبركاته شكرا جدا على اهتمامك بتطوير ال extension ولكن بعض التغييرات اللي ضفتها بتغير من هدف ال extension خليني اناقش معاك بعض منهم
> 
> اضافه اذكار جديده شيء رائع و هتاكد اني اضيفهم ان شاء الله تغيير الوقت اللي موجود في ال options: خليني ااقولك ان اول نسخه من ال extension كان الوقت 10 دقايق و كان راي المستخدمين انو كده الوقت قليل جدا وتحول من انو حاجه تساعد الناس تذكر ربنا مع الوقت الكبير اللي بنقضيه على اللاب توب الي انو اصبح notification متكرره مزعجه بتخرجهم عن الحاجه اللي شغالين عليها بالفعل فخلينا نضيف ال optionsلجديده مع الموجوده بالفعل
> 
> بالنسبه لاضافه لوجو جديد شكرا لاهتمامك بالتفاصيل بس في مصمم هيشتغل على حاجه تكون خاصه بينا ان شاء الله
> 
> بالنسبه لل commit اللي مكتوب فيه تغييرات جذريه فهو بعيد كل البعد عن هدف ال extension لانو زي ما ذكرت لحضرتك قبل كده هدف ال extension هو ذكر بسيط وسط زحمه الشغل و اليوم فصعب جدا حد يقعد يقراء القميه بكل ذكر و خليني ااقولك ان في بدايه الامر كنا متعمدين نضيف اذكار قصيره محفوظه من كل الناس تقريبا و بالتالي اما يجي الاشعار المستخدم مش مضطر انو يقراء الذكر كامل و لكن بمجرد عينه ما تلمح اول كلمه يقدر يردد الذكر تلقائيا فعايزين نتجنب وجود كلام كتير داخل ال notification.
> 
> فكره اذكار الصباح و المساء اكثر من رائعه شكرا جدا للاضافه الجميله شكرا جدا مره تانيه على اهتمامك و مشركتك ربنا يتقبل منا و منكم صالح الاعمال
> 
> استاذنك ان امكن pr جديد فقط بالاذاكار الاضافيه اللي حضرتك حابب تضيفها مع جزئئه اذكار الصباح و المساء اما جزئيه تغير التوقيت فمفيش مشكله من اضافه ٥ و ١٠ دقايق لل options لموجوده بالفعل

وعليكم السلام ورحمة الله وبركاته
شكرا لحضرتك علي ردك وإهتمامك 


إذا تسمحي لي بإبداء الرأي 
متفق مع حضرتك في كل كلامك
فقط مختلف مع حضرتك في أمر 
وهو الoptions وده هبينه في أخر كلامي
اما بالنسبة للoptions اللي حضرتك تفضلتي وقمتي بيها 
ف هي مكنتش شغالة او مكنش الوقت بيتغير
وده لسبب بسيط 
حضرتك فقط نسيتي سهوا إنك تعملي variable ياخد القيمة اللي إتحفظت من الoptions ويحطها في ال timeout 
ولذلك مهما قمنا بعمل أي تعديل مش بتأثر فيها 
وحضرتك تقدري تشوفي الكود بنفسك  

انا بالفعل قمت بالكثير من التغييرات علي الإضافة وسجلتهم عندي ويعني خفت ارفعهم ف يعمل لخبطة علي الكود القديم لا قدر الله
وكنت منتظر تعديل حضرتك علي الpr من فترة علشان أبعت الجديد 
ولكن نظرا لإنشغال حضرتك الشديد أعانكِ الله ووفقكِ لما فيه الخير 
و في نفس الوقت حسيت إني رسائلي الكثيرة   واللي بحاول فيه أساعد في تطوير الأداة بتسبب إزعاج لحضرتك  ( إن مكنش كده بالفعل ) لإنه فيه تطويرات كثيرة جدا عاوز أقوم بيها ( منها علي سبيل المثال الإستغناء تماما عن الأذكار من خلال الإشعارات وتكون صوتا يشتغل في الخلفية )   وبقدم إعتذاري عليه ويعلم الله لم أقصد اسبب أي إزعاج.
ف عملت إضافة وذكر واللي فيها قمت بكل التعديلات والتطوير اللي كنت بعتها لحضرتك من فترة والتعديلات الجديدة اللي مبعتهاش وكمان تغيرات في تصميم الإضافة نفسها وبعض التطويرات اللي شغال عليها حاليا،
حضرتك تقدري فضلا وليس أمرا بكل تأكيد تشوفيها من هنا 

https://chrome.google.com/webstore/detail/%D9%88%D8%B0%D9%83%D8%B1/kjealjdnigfhdinijbjbdgabfobkbphf?hl=en&authuser=0

تفكيري ورأي المتواضع إني أخليه هو اللي يتحكم في وقت عرض الإشعارات وأقل حاجة لعرض الإشعارات علشان منعملش أي تشتيت او نتيجة عكسية لا قدر الله هي 15 دقيقة 
ويقدر يختار ( 15 ، 20 ، 30 ، 45 ، 60 ) من إعدادات الإضافة 
وبالتالي حضرتك إذا حسبناها حسبة علي أقل وقت وهو 15 دقيقة هيكون اربع مرات في الساعة وده كافي جدا جدا وفي نفس الوقت مش مشتت بالدرجة المزعجة وبردو عنده كامل الحرية والإختيار في إنه يخلي الإشعارات بالوقت اللي يناسبه. 
حضرتك تقدري تشوفي ده كله علي إضافة وذكر

بالنسبة لتطوير أذكار الصباح والمساء ف حضرتك تقدري تشوفي (بكل تأكيد فضلا مش أمر )عرض ليه من خلال الإضافة وذكر وتطويرات أكثر شغال عليها  حضرتك هتلاقيها في وصف الإضافة 

وإذا عجب حضرتك التعديلات اللي قمت بيها ف هقوم بعمل pr مخصص ليه والغي الباقي كما حضرتك طلبتي. 
في النهاية انا بعتذر لحضرتك إذا تسببت بأي إزعاج.
وبعتذر علي طول الرسالة 
حبيت أوضح لا أكثر 

شكرا لسعة صدرك الطيب 
وجزاكم الله خيرا 
وكام عام وأنتم بخير

2023-07-21 12:42 UTC, nagwan commented
> في النهاية انا بعتذر لحضرتك إذا تسببت بأي إزعاج. وبعتذر علي طول الرسالة حبيت أوضح لا أكثر
> 
> شكرا لسعة صدرك الطيب وجزاكم الله خيرا

بسم الله ما شاء الله انا فعلا سعيده جدا بال extension اللي انت بنيته ربنا ينفع بيك و يتقبل منك 
اتمني تستمر في التطوير فيه و نشره 
افكارك رائعه ما شاء الله 
ربنا يسدد خطاك و ينفع بيك 
و مفيش اي ازعاج ولا حاجه 
هبص على جزئيه ال options  هتاكد انها تكون شغاله باذن الله 
شكرا جدا ليك مره تانيه و بالتوفيق يارب

2023-07-21 16:40 UTC, nagwan commented
> > > > في النهاية انا بعتذر لحضرتك إذا تسببت بأي إزعاج. وبعتذر علي طول الرسالة حبيت أوضح لا أكثر
> > > > شكرا لسعة صدرك الطيب وجزاكم الله خيرا
> > > 
> > > 
> > > بسم الله ما شاء الله انا فعلا سعيده جدا بال extension اللي انت بنيته ربنا ينفع بيك و يتقبل منك اتمني تستمر في التطوير فيه و نشره افكارك رائعه ما شاء الله ربنا يسدد خطاك و ينفع بيك و مفيش اي ازعاج ولا حاجه هبص على جزئيه ال options هتاكد انها تكون شغاله باذن الله شكرا جدا ليك مره تانيه و بالتوفيق يارب
> > 
> > 
> > الله يكرم حضرتك وهي في الأول في الأخر ألأصل كله راجع لحضرتك لإني إشتقيت من الكود اللي حضرتك تفضلتي وقمتي بيه وبنيت عليه ف الفضل لله أولا ثم لحضرتك في الأخر انا معملتش أي شئ ربنا يتقبل ويجعله في ميزان حسناتك بإذن الله وإذا حضرتك تسمحيلي بعرض بعض الأمور المتعلقة بالإضافة فيه إضافة تانية تقوم علي نفس الفكرة عملتها بفضل الله إضافة إسمها موعظة هي فكرتها إنها بتعرض بدل الأذكار مواعظ وحكم من الصحابة والتابعين وغيرهم من الأئمة والسلف الصالح تقدري تشوفيها من هنا ( فضلا أكيد ) https://chrome.google.com/webstore/detail/%D9%85%D9%8E%D9%88%D9%92%D8%B9%D9%90%D8%B8%D9%8E%D8%A9/llccoellhhlbeegbdbmmcfofcaimngdf?hl=en&authuser=0
> > وفيه bot علي telegram عملته بردو بفضل الله إسمه موعظة نفس فكرة الإضافة ولكن هو بيبعت موعظة كل ساعة و بحدثه بإستمرار لإني بخليه يرسل المواعظ من خلال api صممتها بردو فضلا حضرتك تقدري تشوفيها من هنا https://t.me/mawiza_bot الأمر الأخير وبعتذر علي كثرة كلامي هو والله محاولة متواضعة من شخصي المتواضع لنشر العلم والخير وإفادة أكبر عدد ف فيه تطبيق إسلامي شامل تقريبا هو الأول من نوعه شغال عليه انا وبعض الأشقاء من ( السعودية وفلسطين ) التطبيق اللهم بارك فيه كل ما يحتاجه المسلم في يومه من أذكار وتوقيت الصلاة وغيره من المميزات الجميلة جدا ولسه بإذن الله قريب جدا هينزله التحديث الجديد اللي فيه مميزات جميلة جدا علي سبيل المثال بيشغل تسبيحة او إستغفار أو صلاة علي النبي في الخلفية كل مدة معينة يقدر يحددها المستخدم للتطبيق وميزة التذكير بقراءة سورة الكهف ليوم الجمعة والصلاة علي النبي وحاجات اللهم بارك جميلة جدا تقدري حضرتك تشوفيها من هنا ده الموقع الرسمي للتطبيق ومتوفر لأغلب الأنظمة https://altaqwaa.org/
> > بعتذر لحضرتك تاني إذا طولت في كلامي او لا قدر الله سببت أي إزعاج هي كما قلت محاولة مجتهدة مني لنشر العلم والمشاركة فيه ليس إلا جزاكم الله خيرا دمتم بالخير
> 
> بالنسبة لتطبيق التقوي وتجربة أخر مميزاته ف حضرتك تقدري تنزلي التطبيق وتعملي له run من خلال الfork دي اللي تخص شخصي المتواضع واللي بنزل فيها التحديثات اللي بعملها بفضل الله بإستمرار وبداخلها كل التفاصيل لتشغيل التطبيق ( ك وضع مطور ) https://github.com/m-1226/Altaqwaa-Islamic-Desktop-Application

بسم الله ما شاء الله ربنا يزيك علم و يتقبل منك 
شكرا جدا لمشاركة المجهود الجميل يارب 
جزاك الله خيرا كثيرا

2023-07-23 14:34 UTC, m-1226 commented
> > > > > في النهاية انا بعتذر لحضرتك إذا تسببت بأي إزعاج. وبعتذر علي طول الرسالة حبيت أوضح لا أكثر
> > > > > شكرا لسعة صدرك الطيب وجزاكم الله خيرا
> > > > 
> > > > 
> > > > بسم الله ما شاء الله انا فعلا سعيده جدا بال extension اللي انت بنيته ربنا ينفع بيك و يتقبل منك اتمني تستمر في التطوير فيه و نشره افكارك رائعه ما شاء الله ربنا يسدد خطاك و ينفع بيك و مفيش اي ازعاج ولا حاجه هبص على جزئيه ال options هتاكد انها تكون شغاله باذن الله شكرا جدا ليك مره تانيه و بالتوفيق يارب
> > > 
> > > 
> > > الله يكرم حضرتك وهي في الأول في الأخر ألأصل كله راجع لحضرتك لإني إشتقيت من الكود اللي حضرتك تفضلتي وقمتي بيه وبنيت عليه ف الفضل لله أولا ثم لحضرتك في الأخر انا معملتش أي شئ ربنا يتقبل ويجعله في ميزان حسناتك بإذن الله وإذا حضرتك تسمحيلي بعرض بعض الأمور المتعلقة بالإضافة فيه إضافة تانية تقوم علي نفس الفكرة عملتها بفضل الله إضافة إسمها موعظة هي فكرتها إنها بتعرض بدل الأذكار مواعظ وحكم من الصحابة والتابعين وغيرهم من الأئمة والسلف الصالح تقدري تشوفيها من هنا ( فضلا أكيد ) https://chrome.google.com/webstore/detail/%D9%85%D9%8E%D9%88%D9%92%D8%B9%D9%90%D8%B8%D9%8E%D8%A9/llccoellhhlbeegbdbmmcfofcaimngdf?hl=en&authuser=0
> > > وفيه bot علي telegram عملته بردو بفضل الله إسمه موعظة نفس فكرة الإضافة ولكن هو بيبعت موعظة كل ساعة و بحدثه بإستمرار لإني بخليه يرسل المواعظ من خلال api صممتها بردو فضلا حضرتك تقدري تشوفيها من هنا https://t.me/mawiza_bot الأمر الأخير وبعتذر علي كثرة كلامي هو والله محاولة متواضعة من شخصي المتواضع لنشر العلم والخير وإفادة أكبر عدد ف فيه تطبيق إسلامي شامل تقريبا هو الأول من نوعه شغال عليه انا وبعض الأشقاء من ( السعودية وفلسطين ) التطبيق اللهم بارك فيه كل ما يحتاجه المسلم في يومه من أذكار وتوقيت الصلاة وغيره من المميزات الجميلة جدا ولسه بإذن الله قريب جدا هينزله التحديث الجديد اللي فيه مميزات جميلة جدا علي سبيل المثال بيشغل تسبيحة او إستغفار أو صلاة علي النبي في الخلفية كل مدة معينة يقدر يحددها المستخدم للتطبيق وميزة التذكير بقراءة سورة الكهف ليوم الجمعة والصلاة علي النبي وحاجات اللهم بارك جميلة جدا تقدري حضرتك تشوفيها من هنا ده الموقع الرسمي للتطبيق ومتوفر لأغلب الأنظمة https://altaqwaa.org/
> > > بعتذر لحضرتك تاني إذا طولت في كلامي او لا قدر الله سببت أي إزعاج هي كما قلت محاولة مجتهدة مني لنشر العلم والمشاركة فيه ليس إلا جزاكم الله خيرا دمتم بالخير
> > 
> > 
> > بالنسبة لتطبيق التقوي وتجربة أخر مميزاته ف حضرتك تقدري تنزلي التطبيق وتعملي له run من خلال الfork دي اللي تخص شخصي المتواضع واللي بنزل فيها التحديثات اللي بعملها بفضل الله بإستمرار وبداخلها كل التفاصيل لتشغيل التطبيق ( ك وضع مطور ) https://github.com/m-1226/Altaqwaa-Islamic-Desktop-Application
> 
> بسم الله ما شاء الله ربنا يزيك علم و يتقبل منك شكرا جدا لمشاركة المجهود الجميل يارب جزاك الله خيرا كثيرا

الله يكرم حضرتك 
ده فضل الله وستره 
رينا يديم فضله وستره علينا وجميعا 
وقريبا إن شاء الله موعظة بوت هيكون علي twitter بإسم mawiza_bot 

وهستأذنك هقفل الpr ده وهفتح واحد جديد بالتعديلات اللي حضرتك طلبتيها ( وهتكون متضمنة بالoptions اللي كلمت حضرتك عنها سابقا

2023-07-23 14:35 UTC, closed without merging

2023-07-23 23:49 UTC, nagwan commented
@m-1226 
السلام عليكم 
مفيش داعي ل pr جديد ادام الافكار دي بالفعل بقت متاحه و اتطبقت في extension تاني الهدف الاستفاده 
فشكرا جدا لمجهودك الجميل

2023-07-24 09:41 UTC, m-1226 commented
> @m-1226 السلام عليكم مفيش داعي ل pr جديد ادام الافكار دي بالفعل بقت متاحه و اتطبقت في extension تاني الهدف الاستفاده فشكرا جدا لمجهودك الجميل

خلاص مفيش أي مشكلة 
اللي حضرتك تشوفيه أكيد
بشكل عام خلال أيام هيكون نزل التحديث الأهم لإضافة وذكر بإذن الله( ميزة تشغيل الأذكار صوتا في الخلفية والإستغناء عن الإشعارات والأصوات هتكون تسبيحة إستغفار صلاة علي النبي ....إلخ) 
وإذا حضرتك مثبتة عندك الإضافة ف هيظهر إعلام ك alert بتجربة التحديث الجديد للإضافة وقتها إن شاء الله 
شكر جدا لحضرتك علي ردك وإهتمامك 
جعله الله في ميزان حسناتك بإذن الله 
 وبعتذر إذا ردودي الكثيرة سببت أي إزعاج لحضرتك
 
هستأذنك 
دمتم بالخير 
السلام عليكم ورحمة الله وبركاته